table Dim_Calendario
	lineageTag: ef421d0d-1e83-47be-baf2-0739a47038c7

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0acc74db-7a06-4dcd-939a-a50b53db275a
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: fd8aa6b5-791c-40f2-bf2a-530eeb0eb915
			defaultHierarchy: LocalDateTable_c7d20a17-3eab-4e8d-b522-918d55e315a1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 956a2219-8483-40c0-9b26-6cfa9bf290bd
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: e6039aee-2476-4746-a020-7f5ade263f4f
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 74444f83-a1b3-4558-83c2-1db3c8a54bbd
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: d53d0939-6a5a-4cce-bc2c-595290f59adf
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: eded486f-1c06-4391-ae58-5a7febbd7abe
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\MAURICIO MONTES\Escritorio\MauricioMontes-00042823-Dashboard\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

